# Default values for chart-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
chart-cloud:
  replicaCount: 1

  image:
    repository: ${deployment_image}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

mysql:

  image:
    repository: fsadykov/centos_mysql
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306
    serviceName: chart-cloud-mysql-service

nameOverride: ""
fullnameOverride: ""

  
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
    - ${deployment_endpoint}
    tls: 
    - secretName: cloud-tls
      hosts:
       - ${deployment_endpoint}



globalEnvironments:
  enabled: true
  environments:

  - name: MYSQL_USER
    value: ${mysql_user}

  - name: MYSQL_DATABASE
    value: ${mysql_database}

  - name: MYSQL_PASSWORD
    value: ${mysql_password}
  - name: MYSQL_HOST
    value: ${mysql_host}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets:
  enabled: true
  allSecrets:
  - name: nexus-creds

  
  
  
  