apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.serviceName }}
  labels:
    app.kubernetes.io/name: {{ include "chart-cloud.name" . }}
    helm.sh/chart: {{ include "chart-cloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "chart-cloud.name" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}-mysql